"""add tours and concerts tables

Revision ID: 31f71553507a
Revises: 6937190c868e
Create Date: 2026-07-01 18:50:13.231410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31f71553507a'
down_revision = '6937190c868e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tours',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tours_name'), ['name'], unique=True)

    op.create_table('concerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tour_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('venue', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tour_id', 'venue', 'starts_at', name='uq_concerts_tour_venue_starts_at')
    )
    with op.batch_alter_table('concerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concerts_tour_id'), ['tour_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concerts_tour_id'))

    op.drop_table('concerts')
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tours_name'))

    op.drop_table('tours')
    # ### end Alembic commands ###
