"""replace cover/avatar color presets with cover image upload

Revision ID: 6a48e0277578
Revises: 7df28d21da74
Create Date: 2026-07-02 19:07:45.182110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a48e0277578'
down_revision = '7df28d21da74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('cover_image_public_id', sa.String(length=255), nullable=True))
        batch_op.drop_column('cover_color')
        batch_op.drop_column('avatar_color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_color', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cover_color', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('cover_image_public_id')
        batch_op.drop_column('cover_image_url')

    # ### end Alembic commands ###
