"""add follows, friend_requests, friendships; attendance gains open_to_connect

Revision ID: 771113ae2c94
Revises: 1cb1437ba221
Create Date: 2026-07-01 21:20:27.462747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '771113ae2c94'
down_revision = '1cb1437ba221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follower_id', sa.Uuid(), nullable=False),
    sa.Column('followed_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('follower_id != followed_id', name='ck_follows_no_self_follow'),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.create_table('friend_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('receiver_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', name='friend_request_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('sender_id != receiver_id', name='ck_friend_requests_no_self_request'),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('friend_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_friend_requests_receiver_id'), ['receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_friend_requests_sender_id'), ['sender_id'], unique=False)

    op.create_table('friendships',
    sa.Column('user_low_id', sa.Uuid(), nullable=False),
    sa.Column('user_high_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('user_low_id < user_high_id', name='ck_friendships_ordered_pair'),
    sa.ForeignKeyConstraint(['user_high_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_low_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_low_id', 'user_high_id')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('open_to_connect', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('open_to_connect')

    op.drop_table('friendships')
    with op.batch_alter_table('friend_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friend_requests_sender_id'))
        batch_op.drop_index(batch_op.f('ix_friend_requests_receiver_id'))

    op.drop_table('friend_requests')
    op.drop_table('follows')
    # ### end Alembic commands ###
