"""add messages table

Revision ID: 7fac74c5b714
Revises: 7c11e1abbdae
Create Date: 2026-07-02 08:21:04.435307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fac74c5b714'
down_revision = '7c11e1abbdae'
branch_labels = None
depends_on = None


def upgrade():
    # Add 'message' to the notification_type enum. Alembic's autogenerate
    # doesn't detect Python enum changes on an existing Postgres native
    # ENUM column, so this is hand-written. Postgres requires ADD VALUE to
    # run outside the migration's normal transaction (autocommit_block) —
    # it's allowed inside a transaction on PG 12+, but only as long as the
    # new value is never *used* in that same transaction, which the plain
    # in-transaction form makes easy to violate by accident later.
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'message'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('image_public_id', sa.String(length=255), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sender_id'), ['sender_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_messages_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))

    op.drop_table('messages')
    # ### end Alembic commands ###

    # Not reversed: Postgres has no ADD VALUE ... IF EXISTS / DROP VALUE for
    # enums. Removing 'message' would require rebuilding the type (rename,
    # recreate, migrate column, drop old type) — out of scope for a
    # downgrade path that's rarely exercised in practice.
